### ISSUE TITLE
Implement replace function

### ISSUE THREAD

**Issue by shirai91** [shirai91/lodak#7]
```
_.replace([string=''], pattern, replacement)
```

Replaces matches for pattern in string with replacement.

### Arguments

`[string=''] (string)`: The string to modify.
`pattern (RegExp|string)`: The pattern to replace.
`replacement (Function|string)`: The match replacement.

### Returns

`(string)`: Returns the modified string.

### Example

```javascript
_.replace("Hi Fred", "Fred", "Barney");
// => 'Hi Barney'
```

**Comment by haigv** [comment]
Done
